version: "3.8"

services:
  netrics:
    build: .
    container_name: "netrics"
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    privileged: true

  prometheus:
    image: prom/prometheus:v2.37.0
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.listen-address=:9123"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=90d"
    network_mode: host

  grafana:
    image: grafana/grafana:8.5.6
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_HTTP_PORT=2345
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    network_mode: host

volumes:
  grafana-data:
  prometheus_data:
  netrics-data:
