global:
  scrape_interval: 3s
  evaluation_interval: 3s

scrape_configs:
  - job_name: "netrics"
    static_configs:
      - targets: ["localhost:2112"]
    metrics_path: "/metrics"
    scheme: "http"

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9123"]
