{
 "title": "Netrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "time_range",
    "label": "Time Range",
    "query": "24h,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d,40d,60d,90d"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Data Usage ",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(data_usage_bytes[$time_range])) / 1048576"
    }
   ]
  },
  {
   "title": "Incoming Data",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(data_usage_bytes{direction=\"incoming\"}[$time_range])) / 1048576"
    }
   ]
  },
  {
   "title": "Outgoing Data",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(data_usage_bytes{direction=\"outgoing\"}[$time_range])) / 1048576"
    }
   ]
  },
  {
   "title": "Average Transfer Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(data_usage_bytes[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Top 5 IPs",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum(increase(data_usage_bytes[$time_range])) by (ip))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Data Transfer/s",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(data_usage_bytes[$__rate_interval])) by (direction)/1048576"
    }
   ]
  },
  {
   "title": "Incoming vs Outgoing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(increase(data_usage_bytes[$time_range])) by (direction) / 1048576"
    }
   ]
  },
  {
   "title": "Percentage of Incoming Traffic",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(data_usage_bytes{direction=\"incoming\"}[$time_range])) / sum(increase(data_usage_bytes[$time_range])) * 100"
    }
   ]
  },
  {
   "title": "Outgoing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(increase(data_usage_bytes{direction=\"outgoing\"}[$__rate_interval])) by (ip) / 1048576",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Data Transfer Rate Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "rate(data_usage_bytes[$__rate_interval])/ 1048576",
     "legendFormat": "{{ip}} ({{direction}})"
    }
   ]
  },
  {
   "title": "Total Bytes Transferred (incoming + outgoing) per IP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum(increase(data_usage_bytes{direction=~\"incoming|outgoing\"}[$__rate_interval])) by (ip) / 1048576",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "Incoming ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "sum(increase(data_usage_bytes{direction=\"incoming\"}[$__rate_interval])) by (ip) / 1048576"
    }
   ]
  }
 ]
}